### ISSUE TITLE
Cannot display attributes for comments

### ISSUE THREAD

**Issue by markiiman** [sedp-mis/base-api#1]
Can you please check if there are some bugs around the method eagerLoadRelations in which I refactored? The sql queries are correct, (I used event listener), the output for relations (relations=comment or relations[]=comments) is correct, but for the url `/api/v1/posts?relations[comments][attributes][]=id&relations[comments][attributes][]=text`, it returns null.

Attached are some screenshots of the test cases I've encountered. Thanks :)

![string_comment](https://cloud.githubusercontent.com/assets/17944707/17322872/51021412-58d2-11e6-90b4-655f65fd72d8.png)
![array_comment](https://cloud.githubusercontent.com/assets/17944707/17322874/514b88cc-58d2-11e6-86ea-15f62de35bfe.png)
![array_comment1](https://cloud.githubusercontent.com/assets/17944707/17322875/514d5918-58d2-11e6-95c9-146bebb2a8fb.png)
![query_comments](https://cloud.githubusercontent.com/assets/17944707/17322876/5157dcd0-58d2-11e6-87f2-2373ac94923d.png)

**Comment by ajcastro** [comment]
Is this already resolved, @markii1607?

**Comment by ajcastro** [comment]
This is considered working

**Comment by markiiman** [comment]
Yes Kuya @ajcastro it was already resolved and it is already working

**Comment by markiiman** [comment]
But the problem for that is when the relation defined in the query param is a reference table, it cannot filter the attributes in the relation.

example:

Post model hasMany Comments
Comments model belongsTo Post

URL: GET  /comments?relations[post][attributes][]=text

since Post model doesnt have comments_id in it's table, it returns an error.

code in base-repository:

```
if (is_array($rules) && array_key_exists('attributes', $rules)) {
      $eagerLoads[$relation] = function ($q) use ($rules) {
             if (!in_array($fk = $this->model->getForeignKey(), $rules['attributes'])) {
                       array_push($rules['attributes'], $fk);
              }
              $q->select($rules['attributes']);
       };
 }
```

**Comment by ajcastro** [comment]
Please change your composer.json. It should be like this. There are major changes in the base-repository which is a dependency. You might need to update your code, because it is backwards incompatible.

![image](https://cloud.githubusercontent.com/assets/4918318/19011592/d8b475c4-87cd-11e6-87c2-504d0108d7ce.png)
